<template>
  <div class="about-us-area section-padding-100 clearfix">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-12 col-lg-12">
          <div class="who-we-contant">
            <h4 class="fadeInUp" data-wow-delay="0.3s">
              MyDataCoin Privacy Policy
            </h4>
            <p class="fadeInUp" data-wow-delay="0.4s">
              MyDataCoin (“us”, “we”, or “our”) operates the
              http://www.mydatacoin.io website (the “Service”).
            </p>
            <p>
              This page informs you of our policies regarding collecting, using,
              and disclosing personal data when you use our Service and the
              choices you have associated with that data.
            </p>
            <p>
              We use your data to provide and improve the Service. By using the
              Service, you agree to collect and use information under this
              policy. Unless otherwise defined in this Privacy Policy, terms
              used in this Privacy Policy have the same meanings as in our Terms
              and Conditions, accessible from http://www.mydatacoin.io
            </p>
          </div>

          <div class="who-we-contant">
            <h4 class="fadeInUp" data-wow-delay="0.3s">Definitions</h4>
            <p class="fadeInUp" data-wow-delay="0.4s">
              • Service - is the http://www.mydatacoin.io website operated by
              myData.coin
            </p>
            <p>
              • Personal Data - means data about a living individual who can be
              identified from those data (or from those and other information
              either in our possession or likely to come into our possession).
            </p>
            <p>
              • Usage Data - is data collected automatically either generated by
              the Service or from the Service infrastructure itself (for
              example, the duration of a page visit).
            </p>
            <p>
              • Cookies - are small pieces of data stored on your device
              (computer or mobile device).
            </p>
            <p>
              • Data Controller means the natural or legal person who (either
              alone or jointly or in common with other persons) determines the
              purposes for which and how any personal information is processed.
            </p>
            <p>
              • For this Privacy Policy, we are a Data Controller of your
              Personal Data.
            </p>
            <p>
              • Data Processor (or Service Provider) means any natural or legal
              person who processes the data on behalf of the Data Controller.
            </p>
            <p>
              • We may use the services of various Service Providers to process
              your data more effectively.
            </p>
            <p>
              • Data Subject (or User) - is any living individual using our
              Service and is the subject of Personal Data.
            </p>
          </div>

          <div class="who-we-contant">
            <h4 class="fadeInUp" data-wow-delay="0.3s">
              Information Collection And Use
            </h4>
            <p class="fadeInUp" data-wow-delay="0.4s">
              We collect several different types of information to provide and
              improve our Service to you.
            </p>
          </div>

          <div class="who-we-contant">
            <h4 class="fadeInUp" data-wow-delay="0.3s">
              Types of Data Collected
            </h4>
            <h5>Personal Data</h5>
            <p class="fadeInUp" data-wow-delay="0.4s">
              While using our Service, we may ask you to provide us with certain
              personally identifiable information that can be used to contact or
              identify you (“Personal Data”). Personally identifiable
              information may include, but is not limited to:
            </p>
            <p>• Photo</p>
            <p>• Name and Family name</p>
            <p>• Mobile number</p>
            <p>• Email address</p>
            <p>• Cookies and Usage Data</p>
            <p>
              We may use your Personal Data to contact you with newsletters,
              marketing or promotional materials and other information that may
              be of interest to you. You may opt out of receiving any of these
              communications from us by following the unsubscribe link or
              instructions provided in any email we send or by contacting us.
            </p>
            <h5>Usage Data</h5>
            <p>
              We may also collect information how the Service is accessed and
              used (“Usage Data”). This Usage Data may include information such
              as your computer’s Internet Protocol address (e.g. IP address),
              browser type, browser version, the pages of our Service that you
              visit, the time and date of your visit, the time spent on those
              pages, unique device identifiers and other diagnostic data.
            </p>
            <h5>Tracking & Cookies Data</h5>
            <p>
              We use cookies and similar tracking technologies to track the
              activity on our Service and hold certain information.
            </p>
            <p>
              Cookies are files with a small amount of data, including an
              anonymous unique identifier. Cookies are sent to your browser from
              a website and stored on your device. Tracking technologies also
              used are beacons, tags, and scripts to collect and track
              information and to improve and analyze our Service.
            </p>
            <p>
              You can instruct your browser to refuse all cookies or to indicate
              when a cookie is being sent. However, if you do not accept
              cookies, you may not be able to use some portions of our Service.
            </p>
            <h5>Examples of Cookies we use:</h5>
            <p>
              • Session Cookies. We use Session Cookies to operate our Service.
            </p>
            <p>
              • Preference Cookies. We use Preference Cookies to remember your
              preferences and various settings.
            </p>
            <p>
              • Security Cookies. We use Security Cookies for security purposes.
            </p>
            <p>
              •Advertising Cookies. Advertising Cookies are used to serve you
              with advertisements that may be relevant to you and your
              interests.
            </p>
          </div>

          <div class="who-we-contant">
            <h4 class="fadeInUp" data-wow-delay="0.3s">Use of Data</h4>
            <h5>MyDataCoin uses the collected data for various purposes:</h5>
            <p class="fadeInUp" data-wow-delay="0.4s">
              • To provide and maintain our Service
            </p>
            <p class="fadeInUp" data-wow-delay="0.4s">
              • To notify you about changes to our Service
            </p>
            <p class="fadeInUp" data-wow-delay="0.4s">
              • To allow you to participate in interactive features of our
              Service when you choose to do so
            </p>
            <p class="fadeInUp" data-wow-delay="0.4s">
              • To provide customer support
            </p>
            <p>
              • To gather analysis or valuable information so that we can
              improve our Service
            </p>
            <p>• To monitor the usage of our Service</p>
            <p>• To detect, prevent and address technical issues</p>
            <p>
              • To provide you with news, special offers and general information
              about other goods, services and events which we offer that are
              similar to those that you have already purchased or enquired about
              unless you have opted not to receive such information
            </p>
          </div>

          <div class="who-we-contant">
            <h4 class="fadeInUp" data-wow-delay="0.3s">
              Legal Basis for Processing Personal Data Under General Data
              Protection Regulation (GDPR)
            </h4>
            <p class="fadeInUp" data-wow-delay="0.4s">
              If you are from the European Economic Area (EEA), myData.coin
              legal basis for collecting and using the personal information
              described in this Privacy Policy depends on the Personal Data we
              collect and the specific context in which we collect it.
            </p>
            <p>myData.coin may process your Personal Data because:</p>
            <p>• We need to perform a contract with you</p>
            <p>• You have given us permission to do so</p>
            <p>
              • The processing is in our legitimate interests and it’s not
              overridden by your rights
            </p>
            <p>• For payment processing purposes</p>
            <p>• To comply with the law</p>
          </div>

          <div class="who-we-contant">
            <h4 class="fadeInUp" data-wow-delay="0.3s">Retention of Data</h4>
            <p class="fadeInUp" data-wow-delay="0.4s">
              MyDataCoin will retain your Personal Data only for as long as is
              necessary for the purposes set out in this Privacy Policy. We will
              retain and use your Personal Data to the extent necessary to
              comply with our legal obligations (for example, if we are required
              to retain your data to comply with applicable laws), resolve
              disputes, and enforce our legal agreements and policies.
            </p>
            <p>
              MyDataCoin will also retain Usage Data for internal analysis
              purposes.
            </p>
            <p>
              Usage Data is generally retained for a shorter period of time,
              except when this data is used to strengthen the security or
              improve our Service's functionality, or we are legally obligated
              to retain this data for longer time periods.
            </p>
          </div>

          <div class="who-we-contant">
            <h4 class="fadeInUp" data-wow-delay="0.3s">Transfer Of Data</h4>
            <p class="fadeInUp" data-wow-delay="0.4s">
              Your information, including Personal Data, may be transferred to —
              and maintained on — computers outside your state, province,
              country, or other governmental jurisdiction where the data
              protection laws may differ from those from your jurisdiction.
            </p>
            <p>
              If you are located outside London and choose to provide
              information to us, please note that we transfer the data,
              including Personal Data, to London and process it there.
            </p>
            <p>
              Your consent to this Privacy Policy followed by your submission of
              such information represents your agreement to that transfer.
            </p>
            <p>
              MyDataCoin will take all steps reasonably necessary to ensure that
              your data is treated securely and in accordance with this Privacy
              Policy and no transfer of your Personal Data will take place to an
              organization or a country unless there are adequate controls in
              place including the security of your data and other personal
              information.
            </p>
          </div>

          <div class="who-we-contant">
            <h4 class="fadeInUp" data-wow-delay="0.3s">Disclosure Of Data</h4>
            <h5 class="fadeInUp" data-wow-delay="0.4s">Legal Requirements</h5>
            <p>
              MyDataCoin may disclose your Personal Data in the good faith
              belief that such action is necessary to:
            </p>
            <p>• To comply with a legal obligation</p>
            <p>• To protect and defend the rights or property of MyDataCoin</p>
            <p>
              • To prevent or investigate possible wrongdoing in connection with
              the Service
            </p>
            <p>
              • To protect the personal safety of users of the Service or the
              public
            </p>
            <p>• To protect against legal liability</p>
          </div>

          <div class="who-we-contant">
            <h4 class="fadeInUp" data-wow-delay="0.3s">Security Of Data</h4>
            <p>
              The security of your data is important to us, but remember that no
              method of transmission over the Internet, or method of electronic
              storage is 100% secure. While we strive to use commercially
              acceptable means to protect your Personal Data, we cannot
              guarantee its absolute security.
            </p>
          </div>

          <div class="who-we-contant">
            <h4 class="fadeInUp" data-wow-delay="0.3s">
              Your Data Protection Rights Under General Data Protection
              Regulation (GDPR)
            </h4>
            <p>
              If you are a resident of the European Economic Area (EEA), you
              have certain data protection rights. myData.coin aims to take
              reasonable steps to allow you to correct, amend, delete, or limit
              the use of your Personal Data.
            </p>
            <p>
              If you wish to be informed what Personal Data we hold about you
              and if you want it to be removed from our systems, please contact
              us.
            </p>
            <p>
              In certain circumstances, you have the following data protection
              rights:
            </p>
            <p>
              • The right to access, update or to delete the information we have
              on you. Whenever made possible, you can access, update or request
              deletion of your Personal Data directly within your account
              settings section. If you are unable to perform these actions
              yourself, please contact us to assist you.
            </p>
            <p>
              • The right of rectification. You have the right to have your
              information rectified if that information is inaccurate or
              incomplete.
            </p>
            <p>
              • The right to object. You have the right to object to our
              processing of your Personal Data.
            </p>
            <p>
              • The right of restriction. You have the right to request that we
              restrict the processing of your personal information.
            </p>
            <p>
              • The right to data portability. You have the right to be provided
              with a copy of the information we have on you in a structured,
              machine-readable and commonly used format.
            </p>
            <p>
              • The right to withdraw consent. You also have the right to
              withdraw your consent at any time where myData.coin relied on your
              consent to process your personal information.
            </p>
            <p>
              Please note that we may ask you to verify your identity before
              responding to such requests.
            </p>
            <p>
              You have the right to complain to a Data Protection Authority
              about our collection and use of your Personal Data. For more
              information, please contact your local data protection authority
              in the European Economic Area (EEA).
            </p>
          </div>

          <div class="who-we-contant">
            <h4 class="fadeInUp" data-wow-delay="0.3s">Service Providers</h4>
            <p>
              We may employ third party companies and individuals to facilitate
              our Service (“Service Providers”), to provide the Service on our
              behalf, to perform Service-related services or to assist us in
              analyzing how our Service is used. These third parties have access
              to your Personal Data only to perform these tasks on our behalf
              and are obligated not to disclose or use it for any other purpose.
            </p>
          </div>

          <div class="who-we-contant">
            <h4 class="fadeInUp" data-wow-delay="0.3s">Analytics</h4>
            <p>
              We may use third-party Service Providers to monitor and analyze
              the use of our Service.
            </p>
            <p>• Google Analytics</p>
            <p>
              • Google Analytics is a web analytics service offered by Google
              that tracks and reports website traffic. Google uses the data
              collected to track and monitor the use of our Service. This data
              is shared with other Google services. Google may use the collected
              data to contextualize and personalize the ads of its own
              advertising network.
            </p>
            <p>
              • You can opt-out of having made your activity on the Service
              available to Google Analytics by installing the Google Analytics
              opt- out browser add-on. The add-on prevents the Google Analytics
              JavaScript (ga.js, analytics.js, and dc.js) from sharing
              information with Google Analytics about visits activity. For more
              information on the privacy practices of Google, please visit the
              Google Privacy & Terms web page:
              http://www.google.com/intl/en/policies/ privacy
            </p>
          </div>

          <div class="who-we-contant">
            <h4 class="fadeInUp" data-wow-delay="0.3s">Children’s Privacy</h4>
            <p>
              Our Service does not address anyone under the age of 18
              (“Children”). We do not knowingly collect personally identifiable
              information from anyone under the age of 18. If you are a parent
              or guardian and you are aware that your Children has provided us
              with Personal Data, please contact us. If we become aware that we
              have collected Personal Data from children without verification of
              parental consent, we take steps to remove that information from
              our servers.
            </p>
          </div>

          <div class="who-we-contant">
            <h4 class="fadeInUp" data-wow-delay="0.3s">
              Changes To This Privacy Policy
            </h4>
            <p>
              We may update our Privacy Policy from time to time. We will notify
              you of any changes by posting the new Privacy Policy on this page.
            </p>
            <p>
              We will let you know via email and/or a prominent notice on our
              Service, prior to the change becoming effective and update the
              “effective date” at the top of this Privacy Policy.
            </p>
            <p>
              You are advised to review this Privacy Policy periodically for any
              changes. Changes to this Privacy Policy are effective when they
              are posted on this page.
            </p>
          </div>

          <p>Effective date: 1 April 2022</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Privacy",
};
</script>